title: yeongpyo 기술 로그
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
- title: Category
  url: /Category
- title: Tag
  url: /Tag

social:
   github: baeyeongpyo
   twitter:
   facebook:
   email:

google_analytics: "UA-58263416-1"
